olx_html_page = "https://www.olx.pl/elektronika/komputery/laptopy/krakow/?page=1&search%5Border%5D=created_at%3Adesc"
olx_listing_class ="css-l9drzq"
olx_title_class = "css-1g61gc2"
olx_price_class = "css-uj7mm0"
olx_status_class = "css-iudov9"
olx_location_class = "css-vbz67q"
olx_pagination_class = "css-b6tdh7"
olx_description_class = "css-19duwlz"